// rules.ts + ordering.ts replayed against the Python's recorded answers
// (scripts/rule_vector_cases/rules.py → tests/vectors/rules.ts, generated by scripts/test-mod.sh).
//
// SHELL GUARD. Bash-lane `evaluate` vectors and ordering sequences with a Bash
// event need shell.ts (shellOnly, commandFires, and for ordering also
// executes / receiptSegments / selfDischarging). While shell.ts is the
// scaffold stub those throw "not ported yet"; such vectors are counted as
// waiting, not compared, and turn on by themselves once shell.ts lands. The
// "waiting on shell.ts" test names how many.
import { test, expect } from 'claude-code/testing'
import { VECTORS, type Vector } from './vectors/rules'
import * as R from '../rules'
import { OrderingEngine, armsOn, sessionScoped, type OrderingStore, type FeedEvent } from '../ordering'
import { shellOnly, commandFires } from '../shell'
import { belowRatchet, pyKind } from './vector_checks'
import { postureOrder } from '../engine'
import { judgeResultExcerpt } from '../judge'
import { agentMessage, harnessPrompt } from '../engine'

type Dict = Record<string, unknown>
const HV = '0.110.0'
const NOT_PORTED = /not ported yet/

/** shell.ts's matcher-lane functions answer (not the stub). */
const SHELL_READY = (() => {
  try {
    shellOnly('x')
    commandFires('x', 'x')
    return true
  } catch (e) {
    if (NOT_PORTED.test(String(e))) return false
    throw e
  }
})()

const clone = <T>(v: T): T => (v === undefined ? v : JSON.parse(JSON.stringify(v)))

function canon(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(canon)
  if (v !== null && typeof v === 'object') {
    const out: Dict = {}
    for (const k of Object.keys(v as Dict).sort()) {
      const x = (v as Dict)[k]
      if (x !== undefined) out[k] = canon(x)
    }
    return out
  }
  return v === undefined ? null : v
}
const same = (a: unknown, b: unknown): boolean => JSON.stringify(canon(a)) === JSON.stringify(canon(b))

const hookVersion = (kw: Dict): R.Version | null =>
  'hook_version' in kw ? (kw.hook_version === null ? null : R.versionTuple(kw.hook_version)) : R.versionTuple(HV)

class MemStore implements OrderingStore {
  constructor(public st: unknown, private readonly ok: boolean) {}
  lock() { return this.ok }
  unlock() {}
  read() { return this.st === null ? undefined : clone(this.st) }
  write(s: unknown) { this.st = clone(s) }
}

const feedEvent = (e: Dict): FeedEvent => ({
  hookPhase: e.hook_phase as string,
  tool: e.tool as string,
  cmd: (e.cmd as string) ?? '',
  filePath: (e.file_path as string) ?? '',
  ok: (e.ok as boolean | null) ?? null,
  armed: (e.armed as string | null) ?? null,
})

/** Python's ordering_feed helper, in TS. Throws "waiting" when shell.ts is the stub. */
function orderingFeed(rule: Dict, events: Dict[], state: unknown, lockOk: boolean): Dict[] {
  const store = new MemStore(state === undefined ? null : clone(state), lockOk !== false)
  const eng = new OrderingEngine(store)
  return events.map((ev) => {
    const r = clone(rule)
    const row: Dict = {}
    try {
      row.verdict = eng.feed(r, feedEvent(ev))
    } catch (e) {
      if (NOT_PORTED.test(String(e))) throw new Waiting()
      row.raises = pyKind(e)
    }
    row.gate_msg = r._gate_msg ?? null
    row.legacy = r._legacy_fires ?? null
    row.state = clone(store.st)
    return row
  })
}

class Waiting extends Error {}

function needsShell(v: Vector): boolean {
  if (v.fn !== 'evaluate') return false
  const rule = v.args[0] as Dict
  const kw = v.kwargs
  return kw.hook_phase === 'pre' && rule.on === 'bash' && kw.tool === 'Bash' && !!kw.cmd
}

/** Run one vector through the port: its output, or { threw }. */
function run(v: Vector): unknown {
  const a = v.args as unknown[]
  const kw = v.kwargs as Dict
  switch (v.fn) {
    case 'to_hook_rule':
      return R.toHookRule(a[0], { hookVersion: hookVersion(kw), activeBase: !!kw.active_base })
    case 'degradation':
      return R.degradation(a[0] as Dict, a[1] ?? null, a[2] ?? null, hookVersion(kw))
    case 'degrade':
      return R.degrade(a[0] as Dict, clone(a[1] as Dict | null), a[2] ?? null, (a[3] as string) ?? '',
        { hookVersion: hookVersion(kw), activeBase: !!kw.active_base })
    case 'norm_given': {
      const r = clone(a[0] as Dict)
      return [R.normGiven(r), r]
    }
    case 'given_ok': return R.givenOk(a[0] as Dict, a[1] as R.GivenFacts, (a[2] as R.ReadFacts) ?? null)
    case 'ordering_feed': return orderingFeed(a[0] as Dict, a[1] as Dict[], a[2], a[3] as boolean)
    case 'evaluate':
      return R.evaluate(a[0] as Dict, {
        hookPhase: kw.hook_phase as string, tool: kw.tool as string, cmd: kw.cmd as string | undefined,
        filePath: kw.file_path as string | undefined, body: kw.body as string | undefined,
        resultText: kw.result_text as string | undefined, prompt: kw.prompt as string | undefined,
        added: kw.added === undefined ? null : (kw.added as string | null),
      })
    case 'rx_ok': return R.rxOk(a[0])
    case 'ordering_rx_ok': return R.orderingRxOk(a[0] as Dict)
    case 'matcher_unsupported': return R.matcherUnsupported(a[0])
    case 'given_unsupported': return R.givenUnsupported(a[0])
    case 'given_supported': return R.givenSupported(a[0] as Dict)
    case 'ordering_unsupported': return R.orderingUnsupported(a[0])
    case 'given_norm': return R.givenNorm(a[0])
    case 'version_tuple': return R.versionTuple(a[0])
    case '_book_facts': return R.bookFacts(a[0] as Dict)
    case 'book_rank': return R.bookRank(a[0] as Dict)
    case '_clean_text': return R.cleanText(a[0])
    case '_one_line': return R.oneLine(a[0])
    case '_version_of': return R.versionOf(a[0])
    case 'disclosure_desc': return R.disclosureDesc(a[0] as Dict)
    case 'disclosure_line': return R.disclosureLine(a[0] as Dict, !!(kw.blocked ?? a[1]))
    case 'arms_on': return armsOn(a[0] as Dict, a[1] as string, (a[2] as string) ?? '')
    case 'session_scoped': return sessionScoped(a[0] as Dict)
    case 'posture_order': return postureOrder(a[0] as never)
    case 'added_lines': return R.addedLines(a[0], a[1])
    case 'edit_added_text': return R.editAddedText(a[0] as Dict)
    case 'judge_result_excerpt': return judgeResultExcerpt(a[0] as Dict as never, a[1] as string)
    case 'agent_message': return agentMessage(a[0] as string)
    case 'harness_prompt': return harnessPrompt(a[0] as string)
    default: throw new Error(`no port mapped for ${v.fn}`)
  }
}

/** Python's ordering helper records `raises` by exception name; the port's
 *  row carries `pyKind` of what it threw (and no verdict). */
function normalizeFeed(out: unknown): unknown {
  return Array.isArray(out) ? out.map((r: Dict) => ('raises' in r ? { ...r, verdict: undefined } : r)) : out
}

/** `_unportable` is the port's own mark; Python's None for such a row means
 *  the pattern really was invalid (pyre cannot tell the two apart). */
function matchesShaped(got: unknown, want: unknown): boolean {
  if (got && typeof got === 'object' && '_unportable' in (got as Dict)) {
    if (want === null) return true
    const { _unportable, ...rest } = got as Dict
    return same(rest, want)
  }
  return same(got, want)
}

const waiting: string[] = []
// The test environment has a console; its lib typing does not declare one.
const log = (s: string): void => (globalThis as { console?: { log(s: string): void } }).console?.log(s)
const byFn = new Map<string, Vector[]>()
for (const v of VECTORS) {
  if (!byFn.has(v.fn)) byFn.set(v.fn, [])
  byFn.get(v.fn)!.push(v)
}

for (const [fn, vs] of byFn) {
  test(`${fn}: ${vs.length} golden vectors`, () => {
    const fails: string[] = []
    vs.forEach((v, i) => {
      const tag = `${fn}#${i} ${JSON.stringify(v.args).slice(0, 160)} ${JSON.stringify(v.kwargs)}`
      if (needsShell(v) && !SHELL_READY) {
        waiting.push(tag)
        return
      }
      let got: unknown
      try {
        got = run(v)
      } catch (e) {
        if (e instanceof Waiting) {
          waiting.push(tag)
          return
        }
        if (v.raises === undefined) fails.push(`${tag}\n  threw ${String(e)}`)
        else if (pyKind(e) !== v.raises) fails.push(`${tag}\n  threw ${pyKind(e)}; Python raised ${v.raises}`)
        return
      }
      if (v.raises !== undefined) {
        fails.push(`${tag}\n  Python raised ${v.raises}; port returned ${JSON.stringify(got)}`)
        return
      }
      const want = fn === 'ordering_feed' ? normalizeFeed(v.out) : v.out
      const ok = fn === 'to_hook_rule' ? matchesShaped(got, want) : same(got, want)
      if (!ok) fails.push(`${tag}\n  want ${JSON.stringify(canon(want))}\n  got  ${JSON.stringify(canon(got))}`)
    })
    expect(fails).toEqual([])
  })
}

test('vectors loaded', () => {
  // Recorded count (vector_checks.ts): raise it when cases are added.
  expect(belowRatchet('rules', VECTORS.length, 549)).toBeNull()
})

test('vectors waiting on shell.ts (bash lane, ordering receipts/gates)', () => {
  // Not a pass for them: they were not compared. Zero once shell.ts lands.
  log(`rules.test: ${waiting.length} vector(s) wait on shell.ts` +
    (waiting.length ? ':\n' + waiting.join('\n') : ''))
  // shell.ts has landed: every vector is compared, none may wait.
  expect(SHELL_READY).toBe(true)
  expect(waiting).toEqual([])
})

test('every vector function has a port', () => {
  const unmapped = [...byFn.keys()].filter((fn) => {
    try {
      run({ fn, args: [], kwargs: {} } as Vector)
      return false
    } catch (e) {
      return /no port mapped/.test(String(e))
    }
  })
  expect(unmapped).toEqual([])
})
