#!/usr/bin/env python3
"""What must and must not be filtered out of a transcript before upload.

Run: python3 plugins/memhub/scripts/transcript_filter_test.py

Every fixture here is a VERBATIM record shape taken from a real Claude Code
transcript, because the whole failure mode this guards against is a filter
written against an imagined shape: too loose and it eats user messages, too
tight and it ships ``/model`` as though someone said it.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from transcript_filter import (  # noqa: E402
    drop_command_wrappers,
    is_command_wrapper,
    record_text,
)

FAILURES: list[str] = []


def check(name: str, condition: bool) -> None:
    if not condition:
        FAILURES.append(name)


def user(text, content_blocks: bool = False) -> dict:
    content = [{"type": "text", "text": text}] if content_blocks else text
    return {
        "type": "user",
        "uuid": "u1",
        "cwd": "/Users/dev/xtrace/web",
        "message": {"role": "user", "content": content},
    }


# ── the three real wrapper shapes ─────────────────────────────────────
# Copied byte-for-byte from ~/.claude/projects transcripts.

INVOCATION = (
    "<command-name>/model</command-name>\n"
    "            <command-message>model</command-message>\n"
    "            <command-args></command-args>"
)
STDOUT = (
    "<local-command-stdout>Set model to \x1b[1mSonnet 5\x1b[22m and saved as "
    "your default for new sessions</local-command-stdout>"
)
CAVEAT = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands. DO NOT respond to these messages or "
    "otherwise consider them in your response unless the user explicitly asks "
    "you to.</local-command-caveat>"
)

check("invocation is filtered", is_command_wrapper(user(INVOCATION)))
check("stdout is filtered", is_command_wrapper(user(STDOUT)))
check("caveat is filtered", is_command_wrapper(user(CAVEAT)))

# The client writes content as a bare string for a typed message and as a
# block list once anything structured is attached. Both must be read.
check("block-list content is filtered too",
      is_command_wrapper(user(INVOCATION, content_blocks=True)))


# ── what must survive ─────────────────────────────────────────────────

check("an ordinary message survives",
      not is_command_wrapper(user("cut from origin/main")))

# The exact trap a looser regex falls into: this very conversation discusses
# the tags it filters. Searching anywhere in the text would delete it.
check("a message QUOTING a wrapper tag survives",
      not is_command_wrapper(user(
          "we need to filter out system messages like "
          "/^\\s*<(command-name|command-message)>/ on the plugin side")))

check("a wrapper tag mid-message survives",
      not is_command_wrapper(user(
          "here is what it looks like: <command-name>/model</command-name>")))

# Not symmetric with the above: if a wrapper ever DOES lead a record that also
# carries real prose, keeping it ships some noise; dropping it loses a user
# message that no later flush re-sends.
check("a wrapper WITH real prose beside it is kept",
      not is_command_wrapper(user(
          INVOCATION + "\nand while you're there, bump the version")))

check("assistant records are never filtered",
      not is_command_wrapper({
          "type": "assistant", "uuid": "a1",
          "message": {"role": "assistant", "content": INVOCATION},
      }))

check("sidecar records without a message are untouched",
      not is_command_wrapper({"type": "ai-title", "aiTitle": "Some title"}))


# ── malformed input must not raise ────────────────────────────────────
# This runs inside a Stop hook; an exception here is a traceback in the
# user's session.

for junk in (None, "", 42, [], {}, {"type": "user"},
             {"type": "user", "message": None},
             {"type": "user", "message": {"content": None}},
             {"type": "user", "message": {"content": [{"no": "type"}]}}):
    try:
        is_command_wrapper(junk)
    except Exception as exc:  # noqa: BLE001
        FAILURES.append(f"raised on {junk!r}: {type(exc).__name__}")

check("text of a contentless record is empty", record_text({"type": "user"}) == "")


# ── the list filter ───────────────────────────────────────────────────

records = [
    user("ok, let's work now and pr"),
    user(INVOCATION),
    user(STDOUT),
    {"type": "assistant", "uuid": "a2",
     "message": {"role": "assistant", "content": "on it"}},
    user(CAVEAT),
]
kept = drop_command_wrappers(records)
check("only the wrappers are dropped", len(kept) == 2)
check("order is preserved",
      record_text(kept[0]) == "ok, let's work now and pr")
check("the assistant turn survives", kept[1]["type"] == "assistant")
check("the input list is not mutated", len(records) == 5)
check("an empty list is fine", drop_command_wrappers([]) == [])


# ── against the real transcripts on this machine, if present ──────────
# Not a fixture: proves the filter's rate against actual data, and would fail
# loudly if the client ever changed the wrapper shape.

import glob  # noqa: E402
import json  # noqa: E402

real = sorted(glob.glob(str(
    Path.home() / ".claude" / "projects" / "*" / "*.jsonl"
)))[-4:]
if real:
    seen = dropped = 0
    for path in real:
        for line in open(path, errors="replace"):
            try:
                rec = json.loads(line)
            except Exception:  # noqa: BLE001
                continue
            if rec.get("type") != "user":
                continue
            seen += 1
            if is_command_wrapper(rec):
                dropped += 1
    print(f"real transcripts: {dropped}/{seen} user records filtered")
    check("real transcripts contain wrappers to filter", dropped > 0)
    # A filter eating most of a session means the anchor broke.
    check("the filter is not eating the conversation", dropped < seen * 0.5)
else:
    print("real transcripts: none found, skipped")


print(f"{'FAIL' if FAILURES else 'PASS'}: transcript_filter")
for f in FAILURES:
    print(f"  - {f}")
sys.exit(1 if FAILURES else 0)
