// Shell-text normalisation the rule lanes match against: a port of the pure
// shell helpers in scripts/rulebook_hook.py (and scripts/redact.py). Python
// name → camelCase here, leading underscore dropped; the full map is at the
// bottom of this file. Golden vectors (tests/vectors/shell.ts, generated by scripts/test-mod.sh from
// scripts/rule_vector_cases/shell.py) hold every export to Python's answers.
//
// Python semantics this file reproduces on purpose, because JS differs:
//   * strings are indexed by CODE POINT (Python) not UTF-16 unit (JS): every
//     offset that crosses from one string to another goes through `u2c`.
//   * `\s`, `\w`, `\d`, `\b` are Unicode-aware in Python's `re`; JS's are
//     ASCII. The classes below are Python's (checked against Unicode 16).
//   * `str.strip()` strips Python's whitespace set, not JS `trim()`'s.
//   * `$` without re.M also matches before a final "\n".
//   * `(?i)` folds ı/İ onto i, ſ onto s and K (Kelvin) onto k; JS's `i` flag
//     does not fold all of them, so the case-insensitive redaction patterns
//     spell their letters out instead of using the flag.
//   * `shlex` (POSIX mode, `whitespace_split`, optionally `punctuation_chars`
//     and `#` comments) is ported state for state.
//   * `fnmatch` is ported from 3.14's `translate`, bracket quirks included.
//
// Rule-authored patterns never reach `new RegExp` here: they go through
// pyre.ts (`pySearch`/`pyCompile`). The regexes written natively below are
// the module's own fixed constants.
//
// I/O SPLIT. Some Python functions touch the machine; here they are pure
// cores and the caller supplies the facts:
//   * `bash_reads(cwd, cmd)` reads $HOME (expanduser) and os.getcwd():
//     `bashReads(cwd, cmd, home, processCwd)`. `~user` (another user's home)
//     needs a passwd lookup and is left unexpanded here — Python expands it
//     when the user exists.
//   * `_redirect_base(cwd)` stats and reads <base>/pretest-redirect.json and
//     resolves symlinks: `redirectBase(cwd, facts)` takes the stat result, the
//     parsed JSON, the uid, the clock, and isDir/realpath functions.
//   * `repo_of_call` is git and filesystem walks except its last step, the
//     literal `cd <dir> &&` prefix of a Bash command: `cdPrefixTarget(cmd)`.
//     The caller runs `command_root`/`repo_info` on a non-null answer.
//   * `redact_identities` reads this machine's home: `redactIdentities(text, home)`.

import { pyCompile, pySearch } from './pyre'

// ── Python character classes ────────────────────────────────────────────────

/** Python's `\s` / `str.isspace()` set (identical in Unicode 16). */
const PY_S = '\\t-\\r\\x1c-\\x20\\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000'
const S = `[${PY_S}]`
const NS = `[^${PY_S}]`
/** Python's `\w` for str: `isalnum() or '_'` = categories L*, N*, plus `_`. */
const W_BODY = '\\p{L}\\p{N}_'
const W = `[${W_BODY}]`
/** Python's Unicode `\b`. */
const B = `(?:(?<=${W})(?!${W})|(?<!${W})(?=${W}))`
/** What `(?i)[a-z]` matches in Python beyond ASCII: İ ı ſ K(Kelvin). */
const CI_AZ = 'a-zA-Z\\u0130\\u0131\\u017f\\u212a'
const CI_EXTRA: Record<string, string> = { i: '\\u0130\\u0131', k: '\\u212a', s: '\\u017f' }
/** A word as Python's `(?i)` reads it, letter by letter. */
const ci = (word: string): string =>
  [...word].map((c) => {
    const l = c.toLowerCase()
    return /^[a-z]$/.test(l) ? `[${l}${l.toUpperCase()}${CI_EXTRA[l] ?? ''}]` : c.replace(/[.*+?^${}()|[\]\\/-]/g, '\\$&')
  }).join('')

const SPACE_RX = new RegExp(`^${S}$`, 'u')
const isPySpace = (ch: string): boolean => SPACE_RX.test(ch)

/** Python `str.strip()` / `lstrip()` / `rstrip()` with no argument. */
export function pyStrip(s: string, side: 'both' | 'left' | 'right' = 'both'): string {
  const cs = Array.from(s)
  let a = 0
  let b = cs.length
  if (side !== 'right') while (a < b && isPySpace(cs[a])) a++
  if (side !== 'left') while (b > a && isPySpace(cs[b - 1])) b--
  return cs.slice(a, b).join('')
}

/** Python `str.rstrip(chars)` / `lstrip(chars)`. */
function stripChars(s: string, chars: string, side: 'left' | 'right'): string {
  const cs = Array.from(s)
  if (side === 'right') {
    let b = cs.length
    while (b > 0 && chars.includes(cs[b - 1])) b--
    return cs.slice(0, b).join('')
  }
  let a = 0
  while (a < cs.length && chars.includes(cs[a])) a++
  return cs.slice(a).join('')
}

/** UTF-16 index → code point index, for every index 0..s.length. */
function u2c(s: string): number[] {
  const out = new Array<number>(s.length + 1)
  let cp = 0
  for (let i = 0; i < s.length; i++) {
    out[i] = cp
    const c = s.charCodeAt(i)
    if (c >= 0xd800 && c <= 0xdbff && i + 1 < s.length) {
      const d = s.charCodeAt(i + 1)
      if (d >= 0xdc00 && d <= 0xdfff) {
        out[i + 1] = cp
        i++
      }
    }
    cp++
  }
  out[s.length] = cp
  return out
}

/** Python `s[a:b]` on code points. */
const cpSlice = (s: string, a: number, b?: number): string => Array.from(s).slice(a, b).join('')
const cpLen = (s: string): number => Array.from(s).length

/** Python `str(x)` for the JSON-shaped values the hook formats. */
function pyStr(v: unknown): string {
  if (v === null || v === undefined) return 'None'
  if (v === true) return 'True'
  if (v === false) return 'False'
  return String(v)
}

/** A Python ValueError surfacing from ported code (`int('²')`, shlex).
 *  `pyName` is what the golden-vector tests compare a `raises` row against. */
export class PyValueError extends Error {
  readonly pyName: string = 'ValueError'
  constructor(msg: string) {
    super(msg)
    this.name = 'ValueError'
  }
}

// `str.isdigit()` beyond Nd: superscripts, circled digits and the like.
const DIGIT_RX = new RegExp(
  '^[\\p{Nd}\\u{b2}-\\u{b3}\\u{b9}\\u{1369}-\\u{1371}\\u{19da}\\u{2070}\\u{2074}-\\u{2079}' +
    '\\u{2080}-\\u{2089}\\u{2460}-\\u{2468}\\u{2474}-\\u{247c}\\u{2488}-\\u{2490}\\u{24ea}' +
    '\\u{24f5}-\\u{24fd}\\u{24ff}\\u{2776}-\\u{277e}\\u{2780}-\\u{2788}\\u{278a}-\\u{2792}' +
    '\\u{10a40}-\\u{10a43}\\u{10e60}-\\u{10e68}\\u{11052}-\\u{1105a}\\u{1f100}-\\u{1f10a}]+$',
  'u',
)
const ND_RX = /^\p{Nd}$/u
const pyIsdigit = (s: string): boolean => DIGIT_RX.test(s)

/** Python `int(s)` for a string `isdigit()`/`\d+` already vetted: every Nd
 *  digit of any script counts; a digit that is not decimal raises. */
function pyInt(s: string): number {
  let n = 0
  for (const ch of s) {
    if (!ND_RX.test(ch)) throw new PyValueError(`invalid literal for int(): ${s}`)
    let start = ch.codePointAt(0)!
    // Nd digits come in aligned runs of ten starting at a zero.
    while (ND_RX.test(String.fromCodePoint(start - 1))) start--
    n = n * 10 + ((ch.codePointAt(0)! - start) % 10)
  }
  return n
}

// ── posixpath, as far as the hook uses it ───────────────────────────────────

export function isabs(p: string): boolean {
  return p.startsWith('/')
}

export function join(a: string, ...rest: string[]): string {
  let path = a
  for (const b of rest) {
    if (b.startsWith('/')) path = b
    else if (!path || path.endsWith('/')) path += b
    else path += '/' + b
  }
  return path
}

export function normpath(path: string): string {
  if (path === '') return '.'
  let initial = path.startsWith('/') ? 1 : 0
  if (initial && path.startsWith('//') && !path.startsWith('///')) initial = 2
  const out: string[] = []
  for (const comp of path.split('/')) {
    if (comp === '' || comp === '.') continue
    if (comp !== '..' || (!initial && out.length === 0) || (out.length > 0 && out[out.length - 1] === '..')) out.push(comp)
    else if (out.length) out.pop()
  }
  const joined = '/'.repeat(initial) + out.join('/')
  return joined || '.'
}

export function basename(p: string): string {
  return p.slice(p.lastIndexOf('/') + 1)
}

export function abspath(p: string, processCwd = '/'): string {
  return normpath(isabs(p) ? p : join(processCwd, p))
}

export function relpath(path: string, start: string, processCwd = '/'): string {
  if (!path) throw new PyValueError('no path specified')
  const s = abspath(start, processCwd).split('/').filter(Boolean)
  const p = abspath(path, processCwd).split('/').filter(Boolean)
  let i = 0
  while (i < s.length && i < p.length && s[i] === p[i]) i++
  const rel = [...Array<string>(s.length - i).fill('..'), ...p.slice(i)]
  return rel.length ? join(rel[0], ...rel.slice(1)) : '.'
}

/** `os.path.expanduser` with $HOME = `home`. `~user` is returned unchanged
 *  (Python resolves it through passwd when that user exists). */
export function expanduser(path: string, home: string): string {
  if (!path.startsWith('~')) return path
  let i = path.indexOf('/', 1)
  if (i < 0) i = path.length
  if (i !== 1) return path
  const userhome = stripChars(home, '/', 'right')
  return userhome + path.slice(i) || '/'
}

/** `_under(path, base)`: `path` is `base` or beneath it. */
export function under(path: string, base: string): boolean {
  return path === base || path.startsWith(join(base, ''))
}

// ── shlex (POSIX, whitespace_split) ─────────────────────────────────────────

export class ShlexError extends PyValueError {}

const SH_WS = ' \t\r\n'
const SH_PUNCT = '();<>|&'

/** `list(shlex.shlex(text, posix=True, punctuation_chars=punct))` with
 *  `whitespace_split = True` and `#` comments when `comments`. Throws
 *  ShlexError where Python raises ValueError. */
export function shlexTokens(text: string, punct: boolean, comments: boolean): string[] {
  const chars = Array.from(text)
  let pos = 0
  const P = punct ? SH_PUNCT : ''
  const C = comments ? '#' : ''
  const pushback: string[] = []
  let state: string | null = ' '
  const read = (): string => (pushback.length ? pushback.pop()! : pos < chars.length ? chars[pos++] : '')
  const readline = (): void => {
    while (pos < chars.length) if (chars[pos++] === '\n') break
  }
  const isQuote = (c: string): boolean => c === "'" || c === '"'

  const readToken = (): string | null => {
    let quoted = false
    let escapedstate = ' '
    let token = ''
    for (;;) {
      const nc = read()
      if (state === null) {
        token = ''
        break
      } else if (state === ' ') {
        if (!nc) {
          state = null
          break
        } else if (SH_WS.includes(nc)) {
          if (token || quoted) break
          continue
        } else if (C.includes(nc)) {
          readline()
        } else if (nc === '\\') {
          escapedstate = 'a'
          state = nc
        } else if (P.includes(nc)) {
          token = nc
          state = 'c'
        } else if (isQuote(nc)) {
          state = nc
        } else {
          token = nc
          state = 'a'
        }
      } else if (isQuote(state)) {
        quoted = true
        if (!nc) throw new ShlexError('No closing quotation')
        if (nc === state) state = 'a'
        else if (nc === '\\' && state === '"') {
          escapedstate = state
          state = nc
        } else token += nc
      } else if (state === '\\') {
        if (!nc) throw new ShlexError('No escaped character')
        if (isQuote(escapedstate) && nc !== state && nc !== escapedstate) token += state
        token += nc
        state = escapedstate
      } else {
        // 'a' (word) or 'c' (punctuation run)
        if (!nc) {
          state = null
          break
        } else if (SH_WS.includes(nc)) {
          state = ' '
          if (token || quoted) break
          continue
        } else if (C.includes(nc)) {
          readline()
          state = ' '
          if (token || quoted) break
          continue
        } else if (state === 'c') {
          if (P.includes(nc)) token += nc
          else {
            if (!SH_WS.includes(nc)) pushback.push(nc)
            state = ' '
            break
          }
        } else if (isQuote(nc)) {
          state = nc
        } else if (nc === '\\') {
          escapedstate = 'a'
          state = nc
        } else if (!P.includes(nc)) {
          token += nc
        } else {
          pushback.push(nc)
          state = ' '
          if (token || quoted) break
          continue
        }
      }
    }
    if (!quoted && token === '') return null
    return token
  }

  const out: string[] = []
  for (;;) {
    const t = readToken()
    if (t === null) return out
    out.push(t)
  }
}

/** `shlex.split(s)`: POSIX, no comments, no punctuation splitting. */
export function shlexSplit(s: string): string[] {
  return shlexTokens(s, false, false)
}

/** `_tokens(text)`: shlex with operators as their own tokens, or null when it
 *  does not parse. */
export function tokens(text: string): string[] | null {
  try {
    return shlexTokens(text, true, true)
  } catch (e) {
    if (e instanceof ShlexError) return null
    throw e
  }
}

/** `_segment_op(tok)`: a token made only of `;&|(`. */
export function segmentOp(tok: string): boolean {
  return !!tok && [...tok].every((ch) => ';&|('.includes(ch))
}

/** `_logical_lines(text)`: [line, tokens | null] per line, rejoining lines
 *  that only parse together (a heredoc inside `"$(cat <<'EOF' …)"`). */
export function logicalLines(text: string): [string, string[] | null][] {
  const lines = text.split('\n')
  const out: [string, string[] | null][] = []
  let i = 0
  while (i < lines.length) {
    let done = false
    for (let j = i; j < lines.length; j++) {
      const chunk = lines.slice(i, j + 1).join(' ')
      const toks = tokens(chunk)
      if (toks !== null) {
        out.push([chunk, toks])
        i = j + 1
        done = true
        break
      }
    }
    if (!done) {
      out.push([lines[i], null])
      i++
    }
  }
  return out
}

// ── shell-only text ─────────────────────────────────────────────────────────

/** `_HD_OPEN`: a heredoc opener; the delimiter must be a word, so `x << 2` is a shift. */
export const HD_OPEN = new RegExp(`<<-?${S}*(['"]?)([A-Za-z_]${W}*)\\1`, 'u')

/** shell_only(cmd): heredoc BODY lines dropped, every shell line kept. */
export function shellOnly(cmd: string): string {
  const out: string[] = []
  let skipUntil: string | null = null
  for (const line of cmd.split('\n')) {
    if (skipUntil !== null) {
      if (pyStrip(line) === skipUntil) skipUntil = null
      continue
    }
    out.push(line)
    const m = HD_OPEN.exec(line)
    if (m) skipUntil = m[2]
  }
  return out.join('\n')
}

// ── quotes, escapes, comments, separators ───────────────────────────────────

const QUOTED_RX = new RegExp(`'[^']*'|"(?:\\\\[^\\n]|[^"\\\\])*"`, 'gu')
const ESCAPE_RX = /\\[\s\S]/gu
const COMMENT_RX = new RegExp(`(?<![^${PY_S};&|()}])#[^\\n]*`, 'gu')
const TRAILING_TERMINATOR_RX = new RegExp(`[${PY_S};\\n]+$`, 'u')
const LAST_SEG_SPLIT_RX = /&&|\|\||;|\n|(?<![>&])&(?![>&])/gu

/** trim_terminators(shell): a trailing `;`/newline/space run removed. */
export function trimTerminators(shell: string | null | undefined): string {
  return (shell || '').replace(TRAILING_TERMINATOR_RX, '')
}

/** blank_syntax(text): quote contents and escapes blanked, comments kept,
 *  length preserved in code points. */
export function blankSyntax(text: string | null | undefined): string {
  const blanked = (text || '').replace(QUOTED_RX, (m) => {
    const cs = Array.from(m)
    return cs[0] + ' '.repeat(cs.length - 2) + cs[cs.length - 1]
  })
  return blanked.replace(ESCAPE_RX, '\x01\x01')
}

/** blank_quoted(text): blank_syntax plus `#` comments blanked. */
export function blankQuoted(text: string | null | undefined): string {
  return blankSyntax(text).replace(COMMENT_RX, (m) => ' '.repeat(cpLen(m)))
}

/** last_segment(shell): the final command segment (split on ;, &&, ||, a
 *  background `&`, newline), separators found outside quotes. */
export function lastSegment(shell: string): string {
  const text = trimTerminators(shell)
  const blank = blankQuoted(text)
  const map = u2c(blank)
  let end = 0
  for (const m of blank.matchAll(LAST_SEG_SPLIT_RX)) end = map[m.index! + m[0].length]
  return pyStrip(cpSlice(text, end))
}

/** strip_comments(text): `#` comments blanked, quotes intact, length kept. */
export function stripComments(text: string | null | undefined): string {
  const out = Array.from(text || '')
  const blank = blankSyntax(text)
  const map = u2c(blank)
  for (const m of blank.matchAll(COMMENT_RX)) {
    for (let i = map[m.index!]; i < map[m.index! + m[0].length]; i++) out[i] = ' '
  }
  return out.join('')
}

// ── leading assignments ─────────────────────────────────────────────────────

const ASSIGN_TOKEN_RX = new RegExp(`[A-Za-z_][A-Za-z0-9_]*=(?:'[^']*'|"[^"]*"|${NS}*)${S}*`, 'gu')
const ASSIGN_NAME_RX = /^[A-Za-z_][A-Za-z0-9_]*=/

/** strip_leading_assignments(shell): env assignments that BEGIN a segment
 *  removed, byte for byte identical elsewhere. */
export function stripLeadingAssignments(shell: string): string {
  const out: string[] = []
  for (const line of shell.split('\n')) {
    const toks = tokens(line)
    if (toks === null) {
      out.push(line)
      continue
    }
    const targets: string[] = []
    let atStart = true
    for (const tok of toks) {
      if (atStart && ASSIGN_NAME_RX.test(tok)) {
        targets.push(tok)
        continue
      }
      atStart = segmentOp(tok)
    }
    let stripped = line
    for (const val of targets) {
      for (const m of stripped.matchAll(ASSIGN_TOKEN_RX)) {
        let first: string | undefined
        try {
          first = shlexSplit(m[0])[0]
        } catch (e) {
          if (e instanceof ShlexError) continue
          throw e
        }
        if (first === undefined || first !== val) continue
        stripped = stripped.slice(0, m.index!) + stripped.slice(m.index! + m[0].length)
        break
      }
    }
    out.push(stripped)
  }
  return out.join('\n')
}

/** command_fires(rx, text, not_rx=None, flags=re.I|re.M). Flags as pyre letters.
 *  `rx` fires on the command as written OR with leading assignments removed;
 *  `not_rx` (always re.I) vetoes across the same pair. Comments never count. */
export function commandFires(rx: string, text: string, notRx?: string | null, flags = 'im'): boolean {
  const t = stripComments(text)
  const forms = [t]
  const bare = stripLeadingAssignments(t)
  if (bare !== t) forms.push(bare)
  if (notRx && forms.some((f) => pySearch(notRx, f, 'i'))) return false
  return forms.some((f) => pySearch(rx, f, flags))
}

// ── the ordering gate's receipts (OrderingEngine) ───────────────────────────

const SEPARATOR_RX = /&&|\|\||;|\n|\||(?<![>&])&(?![>&])/gu
const AND_RX = /&&/gu

/** unquoted(text): quoted contents (and comments) removed — `blank_quoted`. */
export function unquoted(text: string | null | undefined): string {
  return blankQuoted(text)
}

/** and_only_segments(shell): the segments of a chain joined ONLY by `&&`, or
 *  [] for anything else. Separators are read on the blanked copy. */
export function andOnlySegments(shell: string): string[] {
  const s = trimTerminators(shell)
  const blank = blankQuoted(s)
  for (const m of blank.matchAll(SEPARATOR_RX)) if (m[0] !== '&&') return []
  const map = u2c(blank)
  const cps = Array.from(s)
  const out: string[] = []
  let pos = 0
  for (const m of blank.matchAll(AND_RX)) {
    out.push(cps.slice(pos, map[m.index!]).join(''))
    pos = map[m.index! + m[0].length]
  }
  out.push(cps.slice(pos).join(''))
  return out.map((x) => pyStrip(x)).filter((x) => x)
}

/** executes(segment, rx): does this segment run the command `rx` describes?
 *  Syntax only — quotes and comments blanked, leading assignments and
 *  grouping dropped; a `!`-negated segment vouches for nothing. */
export function executes(segment: string | null | undefined, rx: string): boolean {
  const inner = stripChars(stripChars(unquoted(segment || ''), '(){} \t', 'left'), '(){} \t', 'right')
  const text = pyStrip(stripLeadingAssignments(inner))
  if (text.startsWith('!')) return false
  return !!text && pySearch(rx, text)
}

/** self_discharging(shell, spec): does this one `&&`-only call run the
 *  required command BEFORE the gated one? */
export function selfDischarging(shell: string, spec: { required_command_rx: string; gated_command_rx: string }): boolean {
  const segs = andOnlySegments(shell)
  const required = segs.findIndex((part) => executes(part, spec.required_command_rx))
  if (required < 0) return false
  return segs.slice(required + 1).some((part) => commandFires(spec.gated_command_rx, unquoted(part), null, ''))
}

/** receipt_segments(shell, whole_chain=False): the segments whose success the
 *  call's exit status vouches for — the last one, unpiped, not backgrounded,
 *  not after `||`; with `wholeChain`, every segment of an `&&`-only chain. */
export function receiptSegments(shell: string, wholeChain = false): string[] {
  const s = trimTerminators(shell)
  if (wholeChain) {
    const segs = andOnlySegments(s)
    if (segs.length) return segs
  }
  const joiners = [...blankQuoted(s).matchAll(LAST_SEG_SPLIT_RX)].map((m) => m[0])
  if (joiners.length && joiners[joiners.length - 1] === '||') return []
  const last = lastSegment(s)
  if (last && !blankQuoted(last).includes('|')) return [last]
  return []
}

// ── files a Bash call reads ─────────────────────────────────────────────────

export const BASH_READ_MAX_FILES = 8
const READ_CMDS = ['cat', 'head', 'tail', 'less', 'more', 'sed']
const REDIRECT_RX = /(?<![0-9&<])>(?!&)|&>|<</u
const SED_RANGE_RX = /^(\p{Nd}+)(?:,(\+)?(\p{Nd}+|\$))?p(?=\n?$)/u
const LINES_FLAG_RX = /^(?:-n|--lines=)(\p{Nd}+)(?=\n?$)|^-(\p{Nd}+)(?=\n?$)/u

/** (lines, flag-value indices) or [null, null]; indices sorted ascending. */
export type LinesUsed = [number | null, number[] | null]

/** _head_tail_lines(args): lines `head`/`tail` print (10 by default, `-N`,
 *  `-n N`, `-nN`, `--lines=N`), or [null, null] for a form it does not name. */
export function headTailLines(args: readonly string[]): LinesUsed {
  let n = 10
  let i = 0
  const used = new Set<number>()
  while (i < args.length) {
    const a = args[i]
    if (a === '-c' || a === '--bytes' || a.startsWith('--bytes=') || a.startsWith('-c')) return [null, null]
    if (a === '-n' || a === '--lines') {
      if (i + 1 >= args.length || !pyIsdigit(args[i + 1])) return [null, null]
      n = pyInt(args[i + 1])
      used.add(i + 1)
      i += 2
      continue
    }
    const m = LINES_FLAG_RX.exec(a)
    if (m) n = pyInt(m[1] || m[2])
    i++
  }
  return [n, [...used].sort((x, y) => x - y)]
}

/** _sed_lines(args): lines a stdout `sed` prints and the indices that are not
 *  files; [null, null] for `-i` or a script this cannot read. */
export function sedLines(args: readonly string[]): LinesUsed {
  if (args.some((a) => a === '-i' || a.startsWith('-i') || a === '--in-place')) return [null, null]
  let quiet = false
  let script: string | null = null
  const used = new Set<number>()
  let i = 0
  while (i < args.length) {
    const a = args[i]
    if (a === '-n' || a === '--quiet' || a === '--silent') quiet = true
    else if (a === '-e' || a === '--expression' || a === '-f' || a === '--file') {
      if (i + 1 < args.length) {
        used.add(i + 1)
        if (a === '-e' || a === '--expression') script = args[i + 1]
      }
      i += 2
      continue
    } else if (a.startsWith('-')) {
      // another flag
    } else if (script === null) {
      script = a
      used.add(i)
    }
    i++
  }
  const sorted = (): number[] => [...used].sort((x, y) => x - y)
  if (script === null) return [null, null]
  if (!quiet) return [null, sorted()]
  const m = SED_RANGE_RX.exec(script.split(' ').join(''))
  if (!m) return [null, null]
  const a = pyInt(m[1])
  const plus = m[2]
  const b = m[3]
  if (b === undefined) return [1, sorted()]
  if (b === '$') return [null, sorted()]
  return [plus ? pyInt(b) + 1 : Math.max(pyInt(b) - a + 1, 0), sorted()]
}

/** bash_reads(cwd, cmd), pure: [path, pulled] per file the call prints into
 *  the context (`pulled` null = every line). `home` is $HOME; `processCwd`
 *  stands in for os.getcwd() when `cwd` is empty. Throws where Python raises
 *  (a non-decimal digit such as `head -n ²`). */
export function bashReads(cwd: string, cmd: string, home: string, processCwd = '/'): [string, number | null][] {
  const out: [string, number | null][] = []
  let here = expanduser(cwd || '', home) || processCwd
  for (const raw of shellOnly(cmd || '').split(/&&|\|\||;|\n/)) {
    const seg = pyStrip(stripLeadingAssignments(pyStrip(raw)))
    if (!seg) continue
    let toks: string[]
    try {
      toks = shlexSplit(seg)
    } catch (e) {
      if (e instanceof ShlexError) continue
      throw e
    }
    if (!toks.length) continue
    if (toks[0] === 'cd') {
      const target = toks.length > 1 ? expanduser(toks[1], home) : expanduser('~', home)
      here = isabs(target) ? target : normpath(join(here, target))
      continue
    }
    if (seg.includes('|') || REDIRECT_RX.test(seg)) continue
    const name = basename(toks[0])
    if (!READ_CMDS.includes(name)) continue
    const args = toks.slice(1)
    let pulled: number | null = null
    let used: number[] | null = []
    if (name === 'head' || name === 'tail') {
      ;[pulled, used] = headTailLines(args)
      if (used === null) continue
    } else if (name === 'sed') {
      ;[pulled, used] = sedLines(args)
      if (used === null) continue
    }
    const skip = new Set(used)
    const files = args.filter((a, i) => !skip.has(i) && a !== '-' && !a.startsWith('-') && !a.includes('<') && !a.includes('>'))
    for (const f of files) {
      let path = expanduser(f, home)
      if (!isabs(path)) path = normpath(join(here, path))
      out.push([path, pulled])
      if (out.length >= BASH_READ_MAX_FILES) return out
    }
  }
  return out
}

// ── the §4b forward-test redirect ───────────────────────────────────────────

export const REDIRECT_MAX_AGE_S = 3600

/** What `_redirect_base` reads off the machine, gathered by the caller from
 *  `<base>/pretest-redirect.json`. */
export type RedirectFacts = {
  /** os.stat of the file; undefined when it is missing or unreadable. */
  stat?: { uid: number; mode: number; mtime: number }
  /** os.getuid(). */
  uid: number
  /** time.time(), seconds. */
  now: number
  /** The parsed JSON; undefined when unreadable or malformed. */
  data?: unknown
  isDir: (p: string) => boolean
  realpath: (p: string) => string
  /** os.getcwd(), for a relative cwd or prefix. */
  processCwd?: string
}

const pyTruthy = (v: unknown): boolean =>
  !(v === undefined || v === null || v === false || v === 0 || v === '' ||
    (Array.isArray(v) && v.length === 0) ||
    (typeof v === 'object' && v !== null && !Array.isArray(v) && Object.keys(v).length === 0))

/** _redirect_base(cwd), pure: the private base a forward test claimed for
 *  `cwd`, or "". Every doubt reads as "no redirect". */
export function redirectBase(cwd: string, f: RedirectFacts): string {
  if (!cwd) return ''
  try {
    const st = f.stat
    if (!st) return ''
    if (st.uid !== f.uid || st.mode & 0o022) return ''
    if (f.now - st.mtime > REDIRECT_MAX_AGE_S) return ''
    const d = f.data
    if (d === undefined || d === null || typeof d !== 'object' || Array.isArray(d)) return '' // d.get raises
    const rec = d as Record<string, unknown>
    const base = pyTruthy(rec.base) ? pyStr(rec.base) : ''
    const prefix = pyTruthy(rec.cwd_prefix) ? pyStr(rec.cwd_prefix) : ''
    if (!base || !prefix || !f.isDir(base)) return ''
    const pc = f.processCwd ?? '/'
    const here = normpath(abspath(cwd, pc))
    if (!(under(here, normpath(abspath(prefix, pc))) && under(f.realpath(here), f.realpath(prefix)))) return ''
    return base
  } catch {
    return ''
  }
}

// ── repo_of_call: the literal `cd <dir> &&` prefix ──────────────────────────

const ARG = `(?:'([^']*)'|"([^"]*)"|([^${PY_S};&|]+))`
const CD_PREFIX = new RegExp(`^${S}*cd${S}+${ARG}${S}*(?:&&|;)`, 'u')

/** The directory a Bash command's leading literal `cd <dir> &&` names, when
 *  repo_of_call would follow it (no `$`, glob, `~` or escape in it), else
 *  null. The caller then resolves `command_root(cwd, command)`. */
export function cdPrefixTarget(command: unknown): string | null {
  if (typeof command !== 'string') return null
  const m = CD_PREFIX.exec(command)
  if (!m || !pyStrip(m[0], 'right').endsWith('&&')) return null
  const target = [m[1], m[2], m[3]].find((g) => g) ?? ''
  if (!target || [...'$`*?[]{}~\\\n\r'].some((c) => target.includes(c))) return null
  return target
}

// ── anchors (§4.7) ──────────────────────────────────────────────────────────

const RE_ESCAPE = new Set([...'()[]{}?*+-|^$\\.&~# \t\n\r\v\f'])

/** Python `re.escape`. */
export function reEscape(s: string): string {
  return [...s].map((c) => (RE_ESCAPE.has(c) ? '\\' + c : c)).join('')
}

/** The Python pattern `anchor_rx(anchor)` compiles, or null for an anchor
 *  with nothing left to match (a bare `/`). */
export function anchorPattern(anchor: string): string | null {
  const core = stripChars(anchor, '/', 'right')
  if (!core) return null
  const tail = anchor.endsWith('/') ? '(?:/|(?![A-Za-z0-9_./-]))' : '(?![A-Za-z0-9_./-])'
  return '(?<![A-Za-z0-9_.-])' + reEscape(core) + tail
}

/** anchor_rx(anchor): the whole-identifier pattern, through pyre. */
export function anchorRx(anchor: string): RegExp | null {
  const p = anchorPattern(anchor)
  return p === null ? null : pyCompile(p)
}

/** anchor_hits(rule, text): the anchors of `rule` in `text` as whole identifiers. */
export function anchorHits(rule: { anchors?: unknown }, text: string | null | undefined): string[] {
  if (!text) return []
  const anchors = rule.anchors
  if (!anchors || !Array.isArray(anchors)) return []
  const out: string[] = []
  for (const a of anchors) {
    if (typeof a !== 'string') continue
    const p = anchorPattern(a)
    if (p !== null && pySearch(p, text)) out.push(a)
  }
  return out
}

// ── path scope (§3.1) and fnmatch ───────────────────────────────────────────

type ClassItems = { neg: boolean; items: [number, number][] }
type GlobPart = { k: 'lit'; c: string } | { k: 'any' } | { k: 'star' } | { k: 'never' } | ({ k: 'class' } & ClassItems)

/** fnmatch's bracket body (`stuff`, as 3.14's translate builds it) read the
 *  way `sre` reads a character class. */
function parseClass(stuff: string[]): ClassItems {
  let i = 0
  let neg = false
  if (stuff[0] === '^') {
    neg = true
    i = 1
  }
  const items: [number, number][] = []
  const item = (): number => {
    if (stuff[i] === '\\') {
      const c = stuff[i + 1]
      i += 2
      return c.codePointAt(0)!
    }
    return stuff[i++].codePointAt(0)!
  }
  while (i < stuff.length) {
    const lo = item()
    if (stuff[i] === '-' && i + 1 < stuff.length) {
      i++
      const hi = item()
      if (hi < lo) throw new PyValueError('bad character range')
      items.push([lo, hi])
    } else items.push([lo, lo])
  }
  return { neg, items }
}

function globParts(patStr: string): GlobPart[] {
  const pat = Array.from(patStr)
  const n = pat.length
  const res: GlobPart[] = []
  let i = 0
  const find = (ch: string, from: number, to: number): number => {
    for (let x = from; x < to; x++) if (pat[x] === ch) return x
    return -1
  }
  const escBackslash = (s: string[]): string[] => s.flatMap((x) => (x === '\\' ? ['\\', '\\'] : [x]))
  const escChunk = (s: string[]): string[] => s.flatMap((x) => (x === '\\' ? ['\\', '\\'] : x === '-' ? ['\\', '-'] : [x]))
  while (i < n) {
    const c = pat[i]
    i++
    if (c === '*') {
      res.push({ k: 'star' })
      while (i < n && pat[i] === '*') i++
    } else if (c === '?') res.push({ k: 'any' })
    else if (c === '[') {
      let j = i
      if (j < n && pat[j] === '!') j++
      if (j < n && pat[j] === ']') j++
      while (j < n && pat[j] !== ']') j++
      if (j >= n) {
        res.push({ k: 'lit', c: '[' })
        continue
      }
      let stuff: string[]
      if (find('-', i, j) < 0) {
        stuff = escBackslash(pat.slice(i, j))
      } else {
        const chunks: string[][] = []
        let k = pat[i] === '!' ? i + 2 : i + 1
        for (;;) {
          k = find('-', k, j)
          if (k < 0) break
          chunks.push(pat.slice(i, k))
          i = k + 1
          k = k + 3
        }
        const chunk = pat.slice(i, j)
        if (chunk.length) chunks.push(chunk)
        else chunks[chunks.length - 1] = [...chunks[chunks.length - 1], '-']
        for (let x = chunks.length - 1; x > 0; x--) {
          const prev = chunks[x - 1]
          if (prev[prev.length - 1].codePointAt(0)! > chunks[x][0].codePointAt(0)!) {
            chunks[x - 1] = [...prev.slice(0, -1), ...chunks[x].slice(1)]
            chunks.splice(x, 1)
          }
        }
        stuff = []
        chunks.forEach((s, x) => {
          if (x) stuff.push('-')
          stuff.push(...escChunk(s))
        })
      }
      i = j + 1
      if (!stuff.length) res.push({ k: 'never' })
      else if (stuff.length === 1 && stuff[0] === '!') res.push({ k: 'any' })
      else {
        stuff = stuff.flatMap((x) => ('&~|'.includes(x) ? ['\\', x] : [x]))
        if (stuff[0] === '!') stuff = ['^', ...stuff.slice(1)]
        else if (stuff[0] === '^' || stuff[0] === '[') stuff = ['\\', ...stuff]
        res.push({ k: 'class', ...parseClass(stuff) })
      }
    } else res.push({ k: 'lit', c })
  }
  return res
}

const GLOB_CACHE = new Map<string, RegExp>()
const hex = (cp: number): string => `\\u{${cp.toString(16)}}`

function globRegExp(pat: string): RegExp {
  let rx = GLOB_CACHE.get(pat)
  if (rx) return rx
  const src = globParts(pat).map((p) => {
    switch (p.k) {
      case 'lit':
        return hex(p.c.codePointAt(0)!)
      case 'any':
        return '[\\s\\S]'
      case 'star':
        return '[\\s\\S]*'
      case 'never':
        return '(?!)'
      case 'class': {
        const body = p.items.map(([a, b]) => (a === b ? hex(a) : `${hex(a)}-${hex(b)}`)).join('')
        if (!body) return p.neg ? '[\\s\\S]' : '(?!)'
        return `[${p.neg ? '^' : ''}${body}]`
      }
    }
  }).join('')
  rx = new RegExp(`^(?:${src})$`, 'u')
  GLOB_CACHE.set(pat, rx)
  return rx
}

/** fnmatch.fnmatch(name, pat) on POSIX (no case folding). Throws where
 *  Python's `re` would reject the translated class. */
export function fnmatch(name: string, pat: string): boolean {
  return globRegExp(pat).test(name)
}

/** path_in_scope(rule, path, root=""): the server's §3.1 path scope —
 *  in-scope AND NOT excluded, fnmatch against the path, its root-relative
 *  form, and `*\/<glob>`. A Bash call (no path) never meets an include scope. */
export function pathInScope(
  rule: { _scope_paths?: unknown; _scope_exclude_paths?: unknown },
  path: string,
  root = '',
  processCwd = '/',
): boolean {
  const list = (v: unknown): string[] => (Array.isArray(v) && v.length ? (v as string[]) : [])
  const inc = list(rule._scope_paths)
  const exc = list(rule._scope_exclude_paths)
  if (!inc.length && !exc.length) return true
  if (!path) return !inc.length
  const cands = [path]
  if (root && path.startsWith(stripChars(root, '/', 'right') + '/')) {
    const rel = relpath(path, root, processCwd)
    if (rel !== path) cands.push(rel)
  }
  const hit = (g: string): boolean => cands.some((c) => fnmatch(c, g) || fnmatch(c, `*/${g}`))
  return (!inc.length || inc.some(hit)) && !exc.some(hit)
}

// ── redaction ───────────────────────────────────────────────────────────────

const VAL = `'[^']*'|"[^"]*"|[^${PY_S}"']+`
const AZ09 = `[${CI_AZ}0-9_\\-]`
const REDACTIONS: [RegExp, string][] = [
  [new RegExp(
    `${B}(${AZ09}*(?:${ci('secret')}|${ci('passwd')}|${ci('password')}|${ci('token')}|${ci('api')}[_\\-]?${ci('key')}|` +
      `${ci('access')}[_\\-]?${ci('key')}|${ci('credential')}))(${S}*[=:]${S}*|${S}+)(${VAL})`, 'gu'), '$1$2<redacted>'],
  [new RegExp(`(${S}-{1,2}(?:${ci('u')}|${ci('user')})[=${PY_S}]+)([^${PY_S}:"']+):(${VAL})`, 'gu'), '$1$2:<redacted>'],
  [new RegExp(`(${S}-{1,2}(?:${ci('u')}|${ci('user')})[=${PY_S}]+)(['"])([^:'"]+):([^'"]*)\\2`, 'gu'), '$1$2$3:<redacted>$2'],
  [new RegExp(`(${ci('authorization')}${S}*:${S}*)(?:${ci('bearer')}|${ci('basic')}|${ci('token')})?${S}*[^${PY_S}"']+`, 'gu'), '$1<redacted>'],
  [new RegExp(`${B}([${CI_AZ}][${CI_AZ}0-9+.\\-]*:\\/\\/)([^${PY_S}:/@]+):([^${PY_S}@]+)@`, 'gu'), '$1$2:<redacted>@'],
  [new RegExp(`${B}(?:sk|pk|rk)-[A-Za-z0-9_\\-]{16,}`, 'gu'), '<redacted>'],
  [new RegExp(`${B}(?:ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{16,}`, 'gu'), '<redacted>'],
  [new RegExp(`${B}AKIA[0-9A-Z]{16}${B}`, 'gu'), '<redacted>'],
  [new RegExp(`${B}xox[abprs]-[A-Za-z0-9\\-]{10,}`, 'gu'), '<redacted>'],
  [new RegExp(`${B}eyJ[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]+`, 'gu'), '<redacted>'],
  [new RegExp(`${B}mhk_[A-Za-z0-9_\\-]{8,}`, 'gu'), '<redacted>'],
]

/** redact_secrets(text): credential-shaped values out of a command. A
 *  denylist, a floor, not a guarantee. Empty and null pass through. */
export function redactSecrets<T extends string | null | undefined>(text: T): T {
  if (!text) return text
  let t: string = text
  for (const [rx, repl] of REDACTIONS) t = t.replace(rx, repl)
  return t as T
}

// scripts/redact.py
const MEMHUB_KEY_RX = new RegExp(`${B}((?:mhk|xtk)_)[A-Za-z0-9_\\-]{16,}`, 'gu')
const PATH_END = `(?=$|[/\\\\${PY_S}'"\`:;,)])`
const HOME_DIR_RX = new RegExp(
  `(?<![${W_BODY}.~\\-])(?:(?:\\/(?:Users|home)\\/|[A-Za-z]:\\\\Users\\\\)[^/\\\\${PY_S}'"\`:;,)]+|\\/root${PATH_END})`, 'gu')
const EMAIL_RX = new RegExp(`[${W_BODY}.+\\-]+@[${W_BODY}\\-]+(?:\\.[${W_BODY}\\-]+)+`, 'gu')
const jsEscape = (s: string): string => s.replace(/[.*+?^${}()|[\]\\/-]/g, '\\$&')

/** redact.redact_text(text): MemHub keys (`mhk_`/`xtk_`), prefix kept. */
export function redactText(text: string): string {
  return text.replace(MEMHUB_KEY_RX, '$1<redacted>')
}

/** redact.redact_identities(text): home directories to `~`, e-mail
 *  addresses to `<email>`. `home` is this machine's $HOME. */
export function redactIdentities(text: string, home: string): string {
  if (!text) return text
  const own = stripChars(expanduser('~', home), '/\\', 'right')
  if (!(cpLen(own) < 2 || own.startsWith('~'))) {
    text = text.replace(new RegExp(`(?<![${W_BODY}.~\\-])${jsEscape(own)}${PATH_END}`, 'gu'), '~')
  }
  return text.replace(HOME_DIR_RX, '~').replace(EMAIL_RX, '<email>')
}

const ECHO_TOKEN_RX = /[A-Za-z0-9_\-./+]{8,}/g
const count = (hay: string, needle: string): number => hay.split(needle).length - 1

/** redacted_tokens(original, redacted): tokens redaction removed a copy of.
 *  Sorted (Python returns a set). */
export function redactedTokens(original: string, redacted: string): string[] {
  if (!original || !redacted) return []
  const toks = new Set(original.match(ECHO_TOKEN_RX) ?? [])
  return [...toks].filter((t) => count(redacted, t) < count(original, t)).sort()
}

/** scrub_tokens(text, tokens). Python iterates a set (hash order, so its own
 *  answer varies run to run when one token contains another); this goes
 *  longest first, so a token inside another never leaves half of it. */
export function scrubTokens(text: string, toks: Iterable<string>): string {
  const order = [...toks].sort((a, b) => b.length - a.length || (a < b ? -1 : a > b ? 1 : 0))
  for (const tok of order) if (text && text.includes(tok)) text = text.split(tok).join('<redacted>')
  return text
}

/** redact_echoes(original, redacted): every further copy of a redacted value. */
export function redactEchoes(original: string, redacted: string): string {
  if (!original || !redacted) return redacted
  return scrubTokens(redacted, redactedTokens(original, redacted))
}

/** judge_redact(text): MemHub keys, identities, then command-line
 *  credentials, then their echoes. `home` is this machine's $HOME. */
export function judgeRedact(text: string | null | undefined, home: string): string {
  if (!text) return ''
  return redactEchoes(text, redactSecrets(redactIdentities(redactText(text), home)))
}

// ── the text the judge and the anchor lane see ──────────────────────────────

export const ANCHOR_HANDLE_CHARS = 400
export const JUDGE_CALL_CHARS = 600

/** main()'s anchor handle for a Bash call: heredoc bodies dropped,
 *  credentials redacted, ≤ 400 code points. */
export function anchorHandle(cmd: string): string {
  if (!cmd) return ''
  return cpSlice(redactSecrets(shellOnly(cmd)), 0, ANCHOR_HANDLE_CHARS)
}

/** judge_fires' `call.text` for a Bash call: `judge_redact(shell_only(cmd))[:600]`. */
export function judgeCallText(cmd: string, home: string): string {
  return cpSlice(judgeRedact(cmd ? shellOnly(cmd) : '', home), 0, JUDGE_CALL_CHARS)
}

const EDIT_READ_TOOLS = ['Edit', 'Write', 'MultiEdit', 'NotebookEdit', 'Read']

/** judge_matched_on(rule, ev, handle, root): what matched, in words. Not redacted. */
export function judgeMatchedOn(
  rule: { on?: unknown; anchors?: unknown },
  ev: { fp?: unknown; tool?: unknown } | null | undefined,
  handle: string,
  root: string,
  processCwd = '/',
): string {
  if (rule.on === 'anchor') {
    const hit = anchorHits(rule, handle)
    return hit.length ? `anchor '${hit.join(', ')}'` : 'anchor'
  }
  let out = `${rule.on === 'result' ? 'output' : pyStr(rule.on)} pattern`
  let path = pyTruthy(ev?.fp) ? (ev!.fp as string) : ''
  if (path && EDIT_READ_TOOLS.includes(ev?.tool as string)) {
    if (root && path.startsWith(stripChars(root, '/', 'right') + '/')) path = relpath(path, root, processCwd)
    out += ` in ${path}`
  }
  return out
}

// ── Python → TS name map ────────────────────────────────────────────────────
//   rulebook_hook.shell_only                 shellOnly
//   rulebook_hook._HD_OPEN                   HD_OPEN
//   rulebook_hook.last_segment               lastSegment
//   rulebook_hook.trim_terminators           trimTerminators
//   rulebook_hook.blank_quoted               blankQuoted
//   rulebook_hook.blank_syntax               blankSyntax
//   rulebook_hook.strip_comments             stripComments
//   rulebook_hook.strip_leading_assignments  stripLeadingAssignments
//   rulebook_hook.command_fires              commandFires
//   rulebook_hook.unquoted                   unquoted
//   rulebook_hook.and_only_segments          andOnlySegments
//   rulebook_hook.executes                   executes
//   rulebook_hook.self_discharging           selfDischarging
//   rulebook_hook.receipt_segments           receiptSegments
//   rulebook_hook._segment_op                segmentOp
//   rulebook_hook._tokens                    tokens
//   rulebook_hook._logical_lines             logicalLines
//   rulebook_hook.bash_reads                 bashReads (pure core: + home, processCwd)
//   rulebook_hook._head_tail_lines           headTailLines
//   rulebook_hook._sed_lines                 sedLines
//   rulebook_hook._redirect_base             redirectBase (pure core: + facts)
//   rulebook_hook._under                     under
//   rulebook_hook.repo_of_call (cd prefix)   cdPrefixTarget
//   rulebook_hook.anchor_rx                  anchorRx / anchorPattern
//   rulebook_hook.anchor_hits                anchorHits
//   rulebook_hook.path_in_scope              pathInScope
//   fnmatch.fnmatch                          fnmatch
//   rulebook_hook.redact_secrets             redactSecrets
//   rulebook_hook.judge_redact               judgeRedact (+ home)
//   rulebook_hook.redact_echoes              redactEchoes
//   rulebook_hook.redacted_tokens            redactedTokens
//   rulebook_hook.scrub_tokens               scrubTokens
//   rulebook_hook.judge_matched_on           judgeMatchedOn
//   redact.redact_text                       redactText
//   redact.redact_identities                 redactIdentities (+ home)
//   main(): redact_secrets(shell_only(cmd))[:400]     anchorHandle
//   judge_fires: judge_redact(shell_only(cmd))[:600]  judgeCallText
//   shlex.split / shlex.shlex                shlexSplit / shlexTokens
//   os.path.*                                normpath, join, isabs, basename, abspath, relpath, expanduser
